<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class AppSiswaTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('app_siswa')->delete();
        
        \DB::table('app_siswa')->insert(array (
            0 => 
            array (
                'id' => 1,
                'user_code' => '853543d6-7222-45de-9dea-7ec9bf089d7a',
                'foto' => NULL,
                'nisn' => '0012345601',
                'nis' => '2425001',
                'nama_lengkap' => 'Ahmad Fauzi',
                'nama_panggilan' => 'Fauzi',
                'bb' => '35.00',
                'tb' => '138.00',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => 'Bandung',
                'tanggal_lahir' => '2012-03-15',
                'agama' => 'Islam',
                'anak_ke' => 1,
                'alamat_peserta_didik' => 'Jl. Merdeka No. 10',
                'nama_ayah' => 'Budi Santoso',
                'nama_ibu' => 'Siti Rahayu',
                'no_hp_ortu' => '081234560001',
                'pekerjaan_ayah' => 'Wiraswasta',
                'pekerjaan_ibu' => 'Ibu Rumah Tangga',
                'alamat' => 'Jl. Merdeka No. 10',
                'kode_pos' => '40111',
                'kecamatan' => 'Coblong',
                'kab_kota' => 'Kota Bandung',
                'provinsi' => 'Jawa Barat',
                'created_at' => '2026-04-15 00:58:35',
                'updated_at' => '2026-04-15 00:58:35',
            ),
            1 => 
            array (
                'id' => 2,
                'user_code' => '54ad6e91-37fc-493e-ac2f-ad1478e690bf',
                'foto' => NULL,
                'nisn' => '0012345602',
                'nis' => '2425002',
                'nama_lengkap' => 'Siti Nur Aisyah',
                'nama_panggilan' => 'Aisyah',
                'bb' => '32.00',
                'tb' => '135.00',
                'jenis_kelamin' => 'P',
                'tempat_lahir' => 'Jakarta',
                'tanggal_lahir' => '2012-07-22',
                'agama' => 'Islam',
                'anak_ke' => 2,
                'alamat_peserta_didik' => 'Jl. Sudirman No. 5',
                'nama_ayah' => 'Dedi Kurniawan',
                'nama_ibu' => 'Rina Wati',
                'no_hp_ortu' => '081234560002',
                'pekerjaan_ayah' => 'PNS',
                'pekerjaan_ibu' => 'Guru',
                'alamat' => 'Jl. Sudirman No. 5',
                'kode_pos' => '40222',
                'kecamatan' => 'Buahbatu',
                'kab_kota' => 'Kota Bandung',
                'provinsi' => 'Jawa Barat',
                'created_at' => '2026-04-15 00:58:35',
                'updated_at' => '2026-04-15 00:58:35',
            ),
            2 => 
            array (
                'id' => 3,
                'user_code' => '763c357b-dafd-4f49-8392-60f111a6fee7',
                'foto' => NULL,
                'nisn' => '0012345603',
                'nis' => '2425003',
                'nama_lengkap' => 'Budi Prasetyo',
                'nama_panggilan' => 'Budi',
                'bb' => '38.00',
                'tb' => '142.00',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => 'Surabaya',
                'tanggal_lahir' => '2012-01-08',
                'agama' => 'Kristen',
                'anak_ke' => 1,
                'alamat_peserta_didik' => 'Jl. Diponegoro No. 20',
                'nama_ayah' => 'Hendra Alam',
                'nama_ibu' => 'Maria Susanti',
                'no_hp_ortu' => '081234560003',
                'pekerjaan_ayah' => 'Dokter',
                'pekerjaan_ibu' => 'Perawat',
                'alamat' => 'Jl. Diponegoro No. 20',
                'kode_pos' => '40333',
                'kecamatan' => 'Antapani',
                'kab_kota' => 'Kota Bandung',
                'provinsi' => 'Jawa Barat',
                'created_at' => '2026-04-15 00:58:35',
                'updated_at' => '2026-04-15 00:58:35',
            ),
            3 => 
            array (
                'id' => 4,
                'user_code' => 'c88e1398-0063-4df6-bb0b-3dba83e0922e',
                'foto' => NULL,
                'nisn' => '0012345604',
                'nis' => '2425004',
                'nama_lengkap' => 'Dewi Lestari',
                'nama_panggilan' => 'Dewi',
                'bb' => '30.00',
                'tb' => '132.00',
                'jenis_kelamin' => 'P',
                'tempat_lahir' => 'Yogyakarta',
                'tanggal_lahir' => '2012-11-30',
                'agama' => 'Islam',
                'anak_ke' => 3,
                'alamat_peserta_didik' => 'Jl. Gatot Subroto No. 8',
                'nama_ayah' => 'Agus Purnomo',
                'nama_ibu' => 'Wulandari',
                'no_hp_ortu' => '081234560004',
                'pekerjaan_ayah' => 'Petani',
                'pekerjaan_ibu' => 'Pedagang',
                'alamat' => 'Jl. Gatot Subroto No. 8',
                'kode_pos' => '40444',
                'kecamatan' => 'Regol',
                'kab_kota' => 'Kota Bandung',
                'provinsi' => 'Jawa Barat',
                'created_at' => '2026-04-15 00:58:35',
                'updated_at' => '2026-04-15 00:58:35',
            ),
            4 => 
            array (
                'id' => 5,
                'user_code' => '9bf39649-9a43-4429-828f-e04ef6773e66',
                'foto' => NULL,
                'nisn' => '0012345605',
                'nis' => '2425005',
                'nama_lengkap' => 'Muhammad Rizki',
                'nama_panggilan' => 'Rizki',
                'bb' => '36.00',
                'tb' => '140.00',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => 'Medan',
                'tanggal_lahir' => '2012-05-19',
                'agama' => 'Islam',
                'anak_ke' => 2,
                'alamat_peserta_didik' => 'Jl. Cihampelas No. 15',
                'nama_ayah' => 'Syahril Nasution',
                'nama_ibu' => 'Fatimah Siregar',
                'no_hp_ortu' => '081234560005',
                'pekerjaan_ayah' => 'TNI',
                'pekerjaan_ibu' => 'Ibu Rumah Tangga',
                'alamat' => 'Jl. Cihampelas No. 15',
                'kode_pos' => '40131',
                'kecamatan' => 'Cidadap',
                'kab_kota' => 'Kota Bandung',
                'provinsi' => 'Jawa Barat',
                'created_at' => '2026-04-15 00:58:35',
                'updated_at' => '2026-04-15 00:58:35',
            ),
            5 => 
            array (
                'id' => 6,
                'user_code' => '40cc61ef-cfef-4335-aa1b-ab433458d125',
                'foto' => NULL,
                'nisn' => '0012345606',
                'nis' => '2425006',
                'nama_lengkap' => 'Putri Rahmawati',
                'nama_panggilan' => 'Putri',
                'bb' => '31.00',
                'tb' => '134.00',
                'jenis_kelamin' => 'P',
                'tempat_lahir' => 'Semarang',
                'tanggal_lahir' => '2012-09-14',
                'agama' => 'Islam',
                'anak_ke' => 1,
                'alamat_peserta_didik' => 'Jl. Pasteur No. 33',
                'nama_ayah' => 'Tri Wahyudi',
                'nama_ibu' => 'Endang Supriyati',
                'no_hp_ortu' => '081234560006',
                'pekerjaan_ayah' => 'Polri',
                'pekerjaan_ibu' => 'Bidan',
                'alamat' => 'Jl. Pasteur No. 33',
                'kode_pos' => '40161',
                'kecamatan' => 'Sukasari',
                'kab_kota' => 'Kota Bandung',
                'provinsi' => 'Jawa Barat',
                'created_at' => '2026-04-15 00:58:35',
                'updated_at' => '2026-04-15 00:58:35',
            ),
            6 => 
            array (
                'id' => 7,
                'user_code' => '2d93e36b-c3dd-46ab-8118-2f988a675a2d',
                'foto' => NULL,
                'nisn' => '0012345607',
                'nis' => '2425007',
                'nama_lengkap' => 'Eko Saputra',
                'nama_panggilan' => 'Eko',
                'bb' => '34.00',
                'tb' => '136.00',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => 'Palembang',
                'tanggal_lahir' => '2012-02-27',
                'agama' => 'Islam',
                'anak_ke' => 4,
                'alamat_peserta_didik' => 'Jl. Kebon Kawung No. 7',
                'nama_ayah' => 'Wahyu Hidayat',
                'nama_ibu' => 'Nurhayati',
                'no_hp_ortu' => '081234560007',
                'pekerjaan_ayah' => 'Buruh',
                'pekerjaan_ibu' => 'Pedagang',
                'alamat' => 'Jl. Kebon Kawung No. 7',
                'kode_pos' => '40172',
                'kecamatan' => 'Andir',
                'kab_kota' => 'Kota Bandung',
                'provinsi' => 'Jawa Barat',
                'created_at' => '2026-04-15 00:58:35',
                'updated_at' => '2026-04-15 00:58:35',
            ),
            7 => 
            array (
                'id' => 8,
                'user_code' => '535dc024-c7ac-46bb-96ef-51e22c31b198',
                'foto' => NULL,
                'nisn' => '0012345608',
                'nis' => '2425008',
                'nama_lengkap' => 'Nurul Hidayah',
                'nama_panggilan' => 'Nurul',
                'bb' => '29.00',
                'tb' => '130.00',
                'jenis_kelamin' => 'P',
                'tempat_lahir' => 'Makassar',
                'tanggal_lahir' => '2012-06-03',
                'agama' => 'Islam',
                'anak_ke' => 2,
                'alamat_peserta_didik' => 'Jl. Ahmad Yani No. 45',
                'nama_ayah' => 'Mansur Daeng',
                'nama_ibu' => 'Hasnawati',
                'no_hp_ortu' => '081234560008',
                'pekerjaan_ayah' => 'Nelayan',
                'pekerjaan_ibu' => 'Ibu Rumah Tangga',
                'alamat' => 'Jl. Ahmad Yani No. 45',
                'kode_pos' => '40183',
                'kecamatan' => 'Batununggal',
                'kab_kota' => 'Kota Bandung',
                'provinsi' => 'Jawa Barat',
                'created_at' => '2026-04-15 00:58:35',
                'updated_at' => '2026-04-15 00:58:35',
            ),
            8 => 
            array (
                'id' => 9,
                'user_code' => '9910297c-a1cd-4269-9f58-f0f09a6bae51',
                'foto' => NULL,
                'nisn' => '0012345609',
                'nis' => '2425009',
                'nama_lengkap' => 'Ridwan Halim',
                'nama_panggilan' => 'Ridwan',
                'bb' => '37.00',
                'tb' => '141.00',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => 'Bogor',
                'tanggal_lahir' => '2012-12-10',
                'agama' => 'Islam',
                'anak_ke' => 1,
                'alamat_peserta_didik' => 'Jl. Laswi No. 12',
                'nama_ayah' => 'Halim Kusuma',
                'nama_ibu' => 'Tini Marlina',
                'no_hp_ortu' => '081234560009',
                'pekerjaan_ayah' => 'Wirausaha',
                'pekerjaan_ibu' => 'Karyawan Swasta',
                'alamat' => 'Jl. Laswi No. 12',
                'kode_pos' => '40271',
                'kecamatan' => 'Batununggal',
                'kab_kota' => 'Kota Bandung',
                'provinsi' => 'Jawa Barat',
                'created_at' => '2026-04-15 00:58:35',
                'updated_at' => '2026-04-15 00:58:35',
            ),
            9 => 
            array (
                'id' => 10,
                'user_code' => '4880d623-7af8-4835-b2b1-e18d6b98cc86',
                'foto' => NULL,
                'nisn' => '0012345610',
                'nis' => '2425010',
                'nama_lengkap' => 'Indah Permata',
                'nama_panggilan' => 'Indah',
                'bb' => '33.00',
                'tb' => '137.00',
                'jenis_kelamin' => 'P',
                'tempat_lahir' => 'Depok',
                'tanggal_lahir' => '2012-04-25',
                'agama' => 'Kristen',
                'anak_ke' => 1,
                'alamat_peserta_didik' => 'Jl. Terusan Jakarta No. 9',
                'nama_ayah' => 'Permata Sari',
                'nama_ibu' => 'Lestari Ningsih',
                'no_hp_ortu' => '081234560010',
                'pekerjaan_ayah' => 'Karyawan BUMN',
                'pekerjaan_ibu' => 'Guru',
                'alamat' => 'Jl. Terusan Jakarta No. 9',
                'kode_pos' => '40282',
                'kecamatan' => 'Arcamanik',
                'kab_kota' => 'Kota Bandung',
                'provinsi' => 'Jawa Barat',
                'created_at' => '2026-04-15 00:58:35',
                'updated_at' => '2026-04-15 00:58:35',
            ),
            10 => 
            array (
                'id' => 11,
                'user_code' => '2abbb8e0-90f2-4a93-9d63-b20e884a0f25',
                'foto' => NULL,
                'nisn' => '0012345611',
                'nis' => '2425011',
                'nama_lengkap' => 'Fajar Nugroho',
                'nama_panggilan' => 'Fajar',
                'bb' => '40.00',
                'tb' => '145.00',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => 'Bekasi',
                'tanggal_lahir' => '2012-08-16',
                'agama' => 'Islam',
                'anak_ke' => 3,
                'alamat_peserta_didik' => 'Jl. Soekarno Hatta No. 200',
                'nama_ayah' => 'Nugroho Santoso',
                'nama_ibu' => 'Sri Mulyani',
                'no_hp_ortu' => '081234560011',
                'pekerjaan_ayah' => 'Teknisi',
                'pekerjaan_ibu' => 'Ibu Rumah Tangga',
                'alamat' => 'Jl. Soekarno Hatta No. 200',
                'kode_pos' => '40223',
                'kecamatan' => 'Gedebage',
                'kab_kota' => 'Kota Bandung',
                'provinsi' => 'Jawa Barat',
                'created_at' => '2026-04-15 00:58:35',
                'updated_at' => '2026-04-15 00:58:35',
            ),
            11 => 
            array (
                'id' => 12,
                'user_code' => '83474cf6-bbdc-48e6-9044-f3939f983c9b',
                'foto' => NULL,
                'nisn' => '0012345612',
                'nis' => '2425012',
                'nama_lengkap' => 'Sari Wulandari',
                'nama_panggilan' => 'Sari',
                'bb' => '28.00',
                'tb' => '129.00',
                'jenis_kelamin' => 'P',
                'tempat_lahir' => 'Tangerang',
                'tanggal_lahir' => '2012-10-07',
                'agama' => 'Islam',
                'anak_ke' => 2,
                'alamat_peserta_didik' => 'Jl. Kiaracondong No. 55',
                'nama_ayah' => 'Wulandari Putra',
                'nama_ibu' => 'Dewi Susanti',
                'no_hp_ortu' => '081234560012',
                'pekerjaan_ayah' => 'Sopir',
                'pekerjaan_ibu' => 'Pedagang',
                'alamat' => 'Jl. Kiaracondong No. 55',
                'kode_pos' => '40274',
                'kecamatan' => 'Kiaracondong',
                'kab_kota' => 'Kota Bandung',
                'provinsi' => 'Jawa Barat',
                'created_at' => '2026-04-15 00:58:35',
                'updated_at' => '2026-04-15 00:58:35',
            ),
            12 => 
            array (
                'id' => 13,
                'user_code' => 'cafb80fd-d0f8-4a41-8189-31f7cf330572',
                'foto' => NULL,
                'nisn' => '0012345613',
                'nis' => '2425013',
                'nama_lengkap' => 'Yoga Pratama',
                'nama_panggilan' => 'Yoga',
                'bb' => '39.00',
                'tb' => '143.00',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => 'Cirebon',
                'tanggal_lahir' => '2011-11-20',
                'agama' => 'Islam',
                'anak_ke' => 1,
                'alamat_peserta_didik' => 'Jl. Buah Batu No. 100',
                'nama_ayah' => 'Pratama Jaya',
                'nama_ibu' => 'Yuli Astuti',
                'no_hp_ortu' => '081234560013',
                'pekerjaan_ayah' => 'Wiraswasta',
                'pekerjaan_ibu' => 'Karyawan Swasta',
                'alamat' => 'Jl. Buah Batu No. 100',
                'kode_pos' => '40264',
                'kecamatan' => 'Buahbatu',
                'kab_kota' => 'Kota Bandung',
                'provinsi' => 'Jawa Barat',
                'created_at' => '2026-04-15 00:58:35',
                'updated_at' => '2026-04-15 00:58:35',
            ),
            13 => 
            array (
                'id' => 14,
                'user_code' => '89be64b0-668e-4f80-93b9-76c00b7b7b96',
                'foto' => NULL,
                'nisn' => '0012345614',
                'nis' => '2425014',
                'nama_lengkap' => 'Melisa Anggraeni',
                'nama_panggilan' => 'Melisa',
                'bb' => '31.00',
                'tb' => '133.00',
                'jenis_kelamin' => 'P',
                'tempat_lahir' => 'Tasikmalaya',
                'tanggal_lahir' => '2012-01-18',
                'agama' => 'Islam',
                'anak_ke' => 2,
                'alamat_peserta_didik' => 'Jl. Ibrahim Adjie No. 30',
                'nama_ayah' => 'Anggraeni Hasan',
                'nama_ibu' => 'Poppy Marlena',
                'no_hp_ortu' => '081234560014',
                'pekerjaan_ayah' => 'PNS',
                'pekerjaan_ibu' => 'Ibu Rumah Tangga',
                'alamat' => 'Jl. Ibrahim Adjie No. 30',
                'kode_pos' => '40275',
                'kecamatan' => 'Kiaracondong',
                'kab_kota' => 'Kota Bandung',
                'provinsi' => 'Jawa Barat',
                'created_at' => '2026-04-15 00:58:35',
                'updated_at' => '2026-04-15 00:58:35',
            ),
            14 => 
            array (
                'id' => 15,
                'user_code' => '0de77961-4d73-4624-b454-d8a9fb87cedc',
                'foto' => NULL,
                'nisn' => '0012345615',
                'nis' => '2425015',
                'nama_lengkap' => 'Dimas Aditya',
                'nama_panggilan' => 'Dimas',
                'bb' => '36.00',
                'tb' => '139.00',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => 'Garut',
                'tanggal_lahir' => '2012-06-29',
                'agama' => 'Islam',
                'anak_ke' => 1,
                'alamat_peserta_didik' => 'Jl. Margahayu Raya No. 17',
                'nama_ayah' => 'Aditya Wibowo',
                'nama_ibu' => 'Komariah',
                'no_hp_ortu' => '081234560015',
                'pekerjaan_ayah' => 'Petani',
                'pekerjaan_ibu' => 'Pedagang',
                'alamat' => 'Jl. Margahayu Raya No. 17',
                'kode_pos' => '40228',
                'kecamatan' => 'Margacinta',
                'kab_kota' => 'Kota Bandung',
                'provinsi' => 'Jawa Barat',
                'created_at' => '2026-04-15 00:58:35',
                'updated_at' => '2026-04-15 00:58:35',
            ),
            15 => 
            array (
                'id' => 16,
                'user_code' => 'f189a23a-e5f8-489d-aeae-288a647cf0ec',
                'foto' => NULL,
                'nisn' => '0012345616',
                'nis' => '2425016',
                'nama_lengkap' => 'Fitriani Rahayu',
                'nama_panggilan' => 'Fitri',
                'bb' => '27.00',
                'tb' => '128.00',
                'jenis_kelamin' => 'P',
                'tempat_lahir' => 'Sukabumi',
                'tanggal_lahir' => '2012-03-05',
                'agama' => 'Islam',
                'anak_ke' => 3,
                'alamat_peserta_didik' => 'Jl. Pelajar Pejuang No. 6',
                'nama_ayah' => 'Rahayu Sunandar',
                'nama_ibu' => 'Neng Aini',
                'no_hp_ortu' => '081234560016',
                'pekerjaan_ayah' => 'Kuli Bangunan',
                'pekerjaan_ibu' => 'Ibu Rumah Tangga',
                'alamat' => 'Jl. Pelajar Pejuang No. 6',
                'kode_pos' => '40263',
                'kecamatan' => 'Lengkong',
                'kab_kota' => 'Kota Bandung',
                'provinsi' => 'Jawa Barat',
                'created_at' => '2026-04-15 00:58:35',
                'updated_at' => '2026-04-15 00:58:35',
            ),
            16 => 
            array (
                'id' => 17,
                'user_code' => '0f1b3b47-8052-446a-9b51-416ea66a01cb',
                'foto' => NULL,
                'nisn' => '0012345617',
                'nis' => '2425017',
                'nama_lengkap' => 'Reza Firmansyah',
                'nama_panggilan' => 'Reza',
                'bb' => '35.00',
                'tb' => '137.00',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => 'Purwokerto',
                'tanggal_lahir' => '2012-09-01',
                'agama' => 'Islam',
                'anak_ke' => 2,
                'alamat_peserta_didik' => 'Jl. Cijawura Hilir No. 25',
                'nama_ayah' => 'Firmansyah Adi',
                'nama_ibu' => 'Lilis Sumiati',
                'no_hp_ortu' => '081234560017',
                'pekerjaan_ayah' => 'Karyawan Swasta',
                'pekerjaan_ibu' => 'Perawat',
                'alamat' => 'Jl. Cijawura Hilir No. 25',
                'kode_pos' => '40287',
                'kecamatan' => 'Buahbatu',
                'kab_kota' => 'Kota Bandung',
                'provinsi' => 'Jawa Barat',
                'created_at' => '2026-04-15 00:58:35',
                'updated_at' => '2026-04-15 00:58:35',
            ),
            17 => 
            array (
                'id' => 18,
                'user_code' => '3b5ca1b9-0b24-46cd-a14f-eb4cd95bf58b',
                'foto' => NULL,
                'nisn' => '0012345618',
                'nis' => '2425018',
                'nama_lengkap' => 'Cantika Permatasari',
                'nama_panggilan' => 'Cantika',
                'bb' => '30.00',
                'tb' => '131.00',
                'jenis_kelamin' => 'P',
                'tempat_lahir' => 'Cianjur',
                'tanggal_lahir' => '2012-12-22',
                'agama' => 'Islam',
                'anak_ke' => 1,
                'alamat_peserta_didik' => 'Jl. Cijagra No. 11',
                'nama_ayah' => 'Permatasari Budi',
                'nama_ibu' => 'Asih Yulianti',
                'no_hp_ortu' => '081234560018',
                'pekerjaan_ayah' => 'Wirausaha',
                'pekerjaan_ibu' => 'Guru',
                'alamat' => 'Jl. Cijagra No. 11',
                'kode_pos' => '40265',
                'kecamatan' => 'Lengkong',
                'kab_kota' => 'Kota Bandung',
                'provinsi' => 'Jawa Barat',
                'created_at' => '2026-04-15 00:58:35',
                'updated_at' => '2026-04-15 00:58:35',
            ),
            18 => 
            array (
                'id' => 19,
                'user_code' => 'ad8dbd3c-467f-47a0-a15d-1d512f46e21b',
                'foto' => NULL,
                'nisn' => '0012345619',
                'nis' => '2425019',
                'nama_lengkap' => 'Andika Surya',
                'nama_panggilan' => 'Andika',
                'bb' => '38.00',
                'tb' => '142.00',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => 'Karawang',
                'tanggal_lahir' => '2012-04-11',
                'agama' => 'Hindu',
                'anak_ke' => 2,
                'alamat_peserta_didik' => 'Jl. Rumah Sakit No. 14',
                'nama_ayah' => 'Surya Darma',
                'nama_ibu' => 'Komang Ayu',
                'no_hp_ortu' => '081234560019',
                'pekerjaan_ayah' => 'Teknisi',
                'pekerjaan_ibu' => 'Ibu Rumah Tangga',
                'alamat' => 'Jl. Rumah Sakit No. 14',
                'kode_pos' => '40256',
                'kecamatan' => 'Cicendo',
                'kab_kota' => 'Kota Bandung',
                'provinsi' => 'Jawa Barat',
                'created_at' => '2026-04-15 00:58:35',
                'updated_at' => '2026-04-15 00:58:35',
            ),
            19 => 
            array (
                'id' => 20,
                'user_code' => '42cde86e-a718-438a-847b-4dc8cac14964',
                'foto' => NULL,
                'nisn' => '0012345620',
                'nis' => '2425020',
                'nama_lengkap' => 'Zahra Azzahra',
                'nama_panggilan' => 'Zahra',
                'bb' => '29.00',
                'tb' => '130.00',
                'jenis_kelamin' => 'P',
                'tempat_lahir' => 'Bandung',
                'tanggal_lahir' => '2012-07-04',
                'agama' => 'Islam',
                'anak_ke' => 1,
                'alamat_peserta_didik' => 'Jl. Setiabudhi No. 50',
                'nama_ayah' => 'Azzahra Kamil',
                'nama_ibu' => 'Nuraeni Siti',
                'no_hp_ortu' => '081234560020',
                'pekerjaan_ayah' => 'Dosen',
                'pekerjaan_ibu' => 'Bidan',
                'alamat' => 'Jl. Setiabudhi No. 50',
                'kode_pos' => '40143',
                'kecamatan' => 'Sukasari',
                'kab_kota' => 'Kota Bandung',
                'provinsi' => 'Jawa Barat',
                'created_at' => '2026-04-15 00:58:35',
                'updated_at' => '2026-04-15 00:58:35',
            ),
        ));
        
        
    }
}