<?php

namespace Database\Seeders;

use App\Models\Siswa;
use Illuminate\Database\Seeder;

class SiswaSeeder extends Seeder
{
    public function run(): void
    {
        $data = [
            ['nisn'=>'0012345601','nis'=>'2425001','nama_lengkap'=>'Ahmad Fauzi','nama_panggilan'=>'Fauzi','jenis_kelamin'=>'L','tempat_lahir'=>'Bandung','tanggal_lahir'=>'2012-03-15','agama'=>'Islam','anak_ke'=>1,'bb'=>35,'tb'=>138,'nama_ayah'=>'Budi Santoso','nama_ibu'=>'Siti Rahayu','no_hp_ortu'=>'081234560001','pekerjaan_ayah'=>'Wiraswasta','pekerjaan_ibu'=>'Ibu Rumah Tangga','alamat_peserta_didik'=>'Jl. Merdeka No. 10','alamat'=>'Jl. Merdeka No. 10','kode_pos'=>'40111','kecamatan'=>'Coblong','kab_kota'=>'Kota Bandung','provinsi'=>'Jawa Barat'],
            ['nisn'=>'0012345602','nis'=>'2425002','nama_lengkap'=>'Siti Nur Aisyah','nama_panggilan'=>'Aisyah','jenis_kelamin'=>'P','tempat_lahir'=>'Jakarta','tanggal_lahir'=>'2012-07-22','agama'=>'Islam','anak_ke'=>2,'bb'=>32,'tb'=>135,'nama_ayah'=>'Dedi Kurniawan','nama_ibu'=>'Rina Wati','no_hp_ortu'=>'081234560002','pekerjaan_ayah'=>'PNS','pekerjaan_ibu'=>'Guru','alamat_peserta_didik'=>'Jl. Sudirman No. 5','alamat'=>'Jl. Sudirman No. 5','kode_pos'=>'40222','kecamatan'=>'Buahbatu','kab_kota'=>'Kota Bandung','provinsi'=>'Jawa Barat'],
            ['nisn'=>'0012345603','nis'=>'2425003','nama_lengkap'=>'Budi Prasetyo','nama_panggilan'=>'Budi','jenis_kelamin'=>'L','tempat_lahir'=>'Surabaya','tanggal_lahir'=>'2012-01-08','agama'=>'Kristen','anak_ke'=>1,'bb'=>38,'tb'=>142,'nama_ayah'=>'Hendra Alam','nama_ibu'=>'Maria Susanti','no_hp_ortu'=>'081234560003','pekerjaan_ayah'=>'Dokter','pekerjaan_ibu'=>'Perawat','alamat_peserta_didik'=>'Jl. Diponegoro No. 20','alamat'=>'Jl. Diponegoro No. 20','kode_pos'=>'40333','kecamatan'=>'Antapani','kab_kota'=>'Kota Bandung','provinsi'=>'Jawa Barat'],
            ['nisn'=>'0012345604','nis'=>'2425004','nama_lengkap'=>'Dewi Lestari','nama_panggilan'=>'Dewi','jenis_kelamin'=>'P','tempat_lahir'=>'Yogyakarta','tanggal_lahir'=>'2012-11-30','agama'=>'Islam','anak_ke'=>3,'bb'=>30,'tb'=>132,'nama_ayah'=>'Agus Purnomo','nama_ibu'=>'Wulandari','no_hp_ortu'=>'081234560004','pekerjaan_ayah'=>'Petani','pekerjaan_ibu'=>'Pedagang','alamat_peserta_didik'=>'Jl. Gatot Subroto No. 8','alamat'=>'Jl. Gatot Subroto No. 8','kode_pos'=>'40444','kecamatan'=>'Regol','kab_kota'=>'Kota Bandung','provinsi'=>'Jawa Barat'],
            ['nisn'=>'0012345605','nis'=>'2425005','nama_lengkap'=>'Muhammad Rizki','nama_panggilan'=>'Rizki','jenis_kelamin'=>'L','tempat_lahir'=>'Medan','tanggal_lahir'=>'2012-05-19','agama'=>'Islam','anak_ke'=>2,'bb'=>36,'tb'=>140,'nama_ayah'=>'Syahril Nasution','nama_ibu'=>'Fatimah Siregar','no_hp_ortu'=>'081234560005','pekerjaan_ayah'=>'TNI','pekerjaan_ibu'=>'Ibu Rumah Tangga','alamat_peserta_didik'=>'Jl. Cihampelas No. 15','alamat'=>'Jl. Cihampelas No. 15','kode_pos'=>'40131','kecamatan'=>'Cidadap','kab_kota'=>'Kota Bandung','provinsi'=>'Jawa Barat'],
            ['nisn'=>'0012345606','nis'=>'2425006','nama_lengkap'=>'Putri Rahmawati','nama_panggilan'=>'Putri','jenis_kelamin'=>'P','tempat_lahir'=>'Semarang','tanggal_lahir'=>'2012-09-14','agama'=>'Islam','anak_ke'=>1,'bb'=>31,'tb'=>134,'nama_ayah'=>'Tri Wahyudi','nama_ibu'=>'Endang Supriyati','no_hp_ortu'=>'081234560006','pekerjaan_ayah'=>'Polri','pekerjaan_ibu'=>'Bidan','alamat_peserta_didik'=>'Jl. Pasteur No. 33','alamat'=>'Jl. Pasteur No. 33','kode_pos'=>'40161','kecamatan'=>'Sukasari','kab_kota'=>'Kota Bandung','provinsi'=>'Jawa Barat'],
            ['nisn'=>'0012345607','nis'=>'2425007','nama_lengkap'=>'Eko Saputra','nama_panggilan'=>'Eko','jenis_kelamin'=>'L','tempat_lahir'=>'Palembang','tanggal_lahir'=>'2012-02-27','agama'=>'Islam','anak_ke'=>4,'bb'=>34,'tb'=>136,'nama_ayah'=>'Wahyu Hidayat','nama_ibu'=>'Nurhayati','no_hp_ortu'=>'081234560007','pekerjaan_ayah'=>'Buruh','pekerjaan_ibu'=>'Pedagang','alamat_peserta_didik'=>'Jl. Kebon Kawung No. 7','alamat'=>'Jl. Kebon Kawung No. 7','kode_pos'=>'40172','kecamatan'=>'Andir','kab_kota'=>'Kota Bandung','provinsi'=>'Jawa Barat'],
            ['nisn'=>'0012345608','nis'=>'2425008','nama_lengkap'=>'Nurul Hidayah','nama_panggilan'=>'Nurul','jenis_kelamin'=>'P','tempat_lahir'=>'Makassar','tanggal_lahir'=>'2012-06-03','agama'=>'Islam','anak_ke'=>2,'bb'=>29,'tb'=>130,'nama_ayah'=>'Mansur Daeng','nama_ibu'=>'Hasnawati','no_hp_ortu'=>'081234560008','pekerjaan_ayah'=>'Nelayan','pekerjaan_ibu'=>'Ibu Rumah Tangga','alamat_peserta_didik'=>'Jl. Ahmad Yani No. 45','alamat'=>'Jl. Ahmad Yani No. 45','kode_pos'=>'40183','kecamatan'=>'Batununggal','kab_kota'=>'Kota Bandung','provinsi'=>'Jawa Barat'],
            ['nisn'=>'0012345609','nis'=>'2425009','nama_lengkap'=>'Ridwan Halim','nama_panggilan'=>'Ridwan','jenis_kelamin'=>'L','tempat_lahir'=>'Bogor','tanggal_lahir'=>'2012-12-10','agama'=>'Islam','anak_ke'=>1,'bb'=>37,'tb'=>141,'nama_ayah'=>'Halim Kusuma','nama_ibu'=>'Tini Marlina','no_hp_ortu'=>'081234560009','pekerjaan_ayah'=>'Wirausaha','pekerjaan_ibu'=>'Karyawan Swasta','alamat_peserta_didik'=>'Jl. Laswi No. 12','alamat'=>'Jl. Laswi No. 12','kode_pos'=>'40271','kecamatan'=>'Batununggal','kab_kota'=>'Kota Bandung','provinsi'=>'Jawa Barat'],
            ['nisn'=>'0012345610','nis'=>'2425010','nama_lengkap'=>'Indah Permata','nama_panggilan'=>'Indah','jenis_kelamin'=>'P','tempat_lahir'=>'Depok','tanggal_lahir'=>'2012-04-25','agama'=>'Kristen','anak_ke'=>1,'bb'=>33,'tb'=>137,'nama_ayah'=>'Permata Sari','nama_ibu'=>'Lestari Ningsih','no_hp_ortu'=>'081234560010','pekerjaan_ayah'=>'Karyawan BUMN','pekerjaan_ibu'=>'Guru','alamat_peserta_didik'=>'Jl. Terusan Jakarta No. 9','alamat'=>'Jl. Terusan Jakarta No. 9','kode_pos'=>'40282','kecamatan'=>'Arcamanik','kab_kota'=>'Kota Bandung','provinsi'=>'Jawa Barat'],
            ['nisn'=>'0012345611','nis'=>'2425011','nama_lengkap'=>'Fajar Nugroho','nama_panggilan'=>'Fajar','jenis_kelamin'=>'L','tempat_lahir'=>'Bekasi','tanggal_lahir'=>'2012-08-16','agama'=>'Islam','anak_ke'=>3,'bb'=>40,'tb'=>145,'nama_ayah'=>'Nugroho Santoso','nama_ibu'=>'Sri Mulyani','no_hp_ortu'=>'081234560011','pekerjaan_ayah'=>'Teknisi','pekerjaan_ibu'=>'Ibu Rumah Tangga','alamat_peserta_didik'=>'Jl. Soekarno Hatta No. 200','alamat'=>'Jl. Soekarno Hatta No. 200','kode_pos'=>'40223','kecamatan'=>'Gedebage','kab_kota'=>'Kota Bandung','provinsi'=>'Jawa Barat'],
            ['nisn'=>'0012345612','nis'=>'2425012','nama_lengkap'=>'Sari Wulandari','nama_panggilan'=>'Sari','jenis_kelamin'=>'P','tempat_lahir'=>'Tangerang','tanggal_lahir'=>'2012-10-07','agama'=>'Islam','anak_ke'=>2,'bb'=>28,'tb'=>129,'nama_ayah'=>'Wulandari Putra','nama_ibu'=>'Dewi Susanti','no_hp_ortu'=>'081234560012','pekerjaan_ayah'=>'Sopir','pekerjaan_ibu'=>'Pedagang','alamat_peserta_didik'=>'Jl. Kiaracondong No. 55','alamat'=>'Jl. Kiaracondong No. 55','kode_pos'=>'40274','kecamatan'=>'Kiaracondong','kab_kota'=>'Kota Bandung','provinsi'=>'Jawa Barat'],
            ['nisn'=>'0012345613','nis'=>'2425013','nama_lengkap'=>'Yoga Pratama','nama_panggilan'=>'Yoga','jenis_kelamin'=>'L','tempat_lahir'=>'Cirebon','tanggal_lahir'=>'2011-11-20','agama'=>'Islam','anak_ke'=>1,'bb'=>39,'tb'=>143,'nama_ayah'=>'Pratama Jaya','nama_ibu'=>'Yuli Astuti','no_hp_ortu'=>'081234560013','pekerjaan_ayah'=>'Wiraswasta','pekerjaan_ibu'=>'Karyawan Swasta','alamat_peserta_didik'=>'Jl. Buah Batu No. 100','alamat'=>'Jl. Buah Batu No. 100','kode_pos'=>'40264','kecamatan'=>'Buahbatu','kab_kota'=>'Kota Bandung','provinsi'=>'Jawa Barat'],
            ['nisn'=>'0012345614','nis'=>'2425014','nama_lengkap'=>'Melisa Anggraeni','nama_panggilan'=>'Melisa','jenis_kelamin'=>'P','tempat_lahir'=>'Tasikmalaya','tanggal_lahir'=>'2012-01-18','agama'=>'Islam','anak_ke'=>2,'bb'=>31,'tb'=>133,'nama_ayah'=>'Anggraeni Hasan','nama_ibu'=>'Poppy Marlena','no_hp_ortu'=>'081234560014','pekerjaan_ayah'=>'PNS','pekerjaan_ibu'=>'Ibu Rumah Tangga','alamat_peserta_didik'=>'Jl. Ibrahim Adjie No. 30','alamat'=>'Jl. Ibrahim Adjie No. 30','kode_pos'=>'40275','kecamatan'=>'Kiaracondong','kab_kota'=>'Kota Bandung','provinsi'=>'Jawa Barat'],
            ['nisn'=>'0012345615','nis'=>'2425015','nama_lengkap'=>'Dimas Aditya','nama_panggilan'=>'Dimas','jenis_kelamin'=>'L','tempat_lahir'=>'Garut','tanggal_lahir'=>'2012-06-29','agama'=>'Islam','anak_ke'=>1,'bb'=>36,'tb'=>139,'nama_ayah'=>'Aditya Wibowo','nama_ibu'=>'Komariah','no_hp_ortu'=>'081234560015','pekerjaan_ayah'=>'Petani','pekerjaan_ibu'=>'Pedagang','alamat_peserta_didik'=>'Jl. Margahayu Raya No. 17','alamat'=>'Jl. Margahayu Raya No. 17','kode_pos'=>'40228','kecamatan'=>'Margacinta','kab_kota'=>'Kota Bandung','provinsi'=>'Jawa Barat'],
            ['nisn'=>'0012345616','nis'=>'2425016','nama_lengkap'=>'Fitriani Rahayu','nama_panggilan'=>'Fitri','jenis_kelamin'=>'P','tempat_lahir'=>'Sukabumi','tanggal_lahir'=>'2012-03-05','agama'=>'Islam','anak_ke'=>3,'bb'=>27,'tb'=>128,'nama_ayah'=>'Rahayu Sunandar','nama_ibu'=>'Neng Aini','no_hp_ortu'=>'081234560016','pekerjaan_ayah'=>'Kuli Bangunan','pekerjaan_ibu'=>'Ibu Rumah Tangga','alamat_peserta_didik'=>'Jl. Pelajar Pejuang No. 6','alamat'=>'Jl. Pelajar Pejuang No. 6','kode_pos'=>'40263','kecamatan'=>'Lengkong','kab_kota'=>'Kota Bandung','provinsi'=>'Jawa Barat'],
            ['nisn'=>'0012345617','nis'=>'2425017','nama_lengkap'=>'Reza Firmansyah','nama_panggilan'=>'Reza','jenis_kelamin'=>'L','tempat_lahir'=>'Purwokerto','tanggal_lahir'=>'2012-09-01','agama'=>'Islam','anak_ke'=>2,'bb'=>35,'tb'=>137,'nama_ayah'=>'Firmansyah Adi','nama_ibu'=>'Lilis Sumiati','no_hp_ortu'=>'081234560017','pekerjaan_ayah'=>'Karyawan Swasta','pekerjaan_ibu'=>'Perawat','alamat_peserta_didik'=>'Jl. Cijawura Hilir No. 25','alamat'=>'Jl. Cijawura Hilir No. 25','kode_pos'=>'40287','kecamatan'=>'Buahbatu','kab_kota'=>'Kota Bandung','provinsi'=>'Jawa Barat'],
            ['nisn'=>'0012345618','nis'=>'2425018','nama_lengkap'=>'Cantika Permatasari','nama_panggilan'=>'Cantika','jenis_kelamin'=>'P','tempat_lahir'=>'Cianjur','tanggal_lahir'=>'2012-12-22','agama'=>'Islam','anak_ke'=>1,'bb'=>30,'tb'=>131,'nama_ayah'=>'Permatasari Budi','nama_ibu'=>'Asih Yulianti','no_hp_ortu'=>'081234560018','pekerjaan_ayah'=>'Wirausaha','pekerjaan_ibu'=>'Guru','alamat_peserta_didik'=>'Jl. Cijagra No. 11','alamat'=>'Jl. Cijagra No. 11','kode_pos'=>'40265','kecamatan'=>'Lengkong','kab_kota'=>'Kota Bandung','provinsi'=>'Jawa Barat'],
            ['nisn'=>'0012345619','nis'=>'2425019','nama_lengkap'=>'Andika Surya','nama_panggilan'=>'Andika','jenis_kelamin'=>'L','tempat_lahir'=>'Karawang','tanggal_lahir'=>'2012-04-11','agama'=>'Hindu','anak_ke'=>2,'bb'=>38,'tb'=>142,'nama_ayah'=>'Surya Darma','nama_ibu'=>'Komang Ayu','no_hp_ortu'=>'081234560019','pekerjaan_ayah'=>'Teknisi','pekerjaan_ibu'=>'Ibu Rumah Tangga','alamat_peserta_didik'=>'Jl. Rumah Sakit No. 14','alamat'=>'Jl. Rumah Sakit No. 14','kode_pos'=>'40256','kecamatan'=>'Cicendo','kab_kota'=>'Kota Bandung','provinsi'=>'Jawa Barat'],
            ['nisn'=>'0012345620','nis'=>'2425020','nama_lengkap'=>'Zahra Azzahra','nama_panggilan'=>'Zahra','jenis_kelamin'=>'P','tempat_lahir'=>'Bandung','tanggal_lahir'=>'2012-07-04','agama'=>'Islam','anak_ke'=>1,'bb'=>29,'tb'=>130,'nama_ayah'=>'Azzahra Kamil','nama_ibu'=>'Nuraeni Siti','no_hp_ortu'=>'081234560020','pekerjaan_ayah'=>'Dosen','pekerjaan_ibu'=>'Bidan','alamat_peserta_didik'=>'Jl. Setiabudhi No. 50','alamat'=>'Jl. Setiabudhi No. 50','kode_pos'=>'40143','kecamatan'=>'Sukasari','kab_kota'=>'Kota Bandung','provinsi'=>'Jawa Barat'],
        ];

        foreach ($data as $row) {
            Siswa::create($row);
        }
    }
}
